asset_sync:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_DIRECTORY:
  run_on_precompile: false
redis:
  host: localhost
  port: 6379
  db: 0
  namespace: booking_portal_dev
sidekiq:
  username:
  password:
