asset_sync:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_DIRECTORY:
  run_on_precompile: false
redis:
  host: localhost
  port: 6379
  db: 0
  namespace: booking_portal_dev
  password:
sidekiq:
  username:
  password:
pusher:
  key: 'fe128113ca13812feaf0'
  secret: 'c74d20f592399a3c6ba6'
  app_id: '501969'
  cluster: 'ap2'
