host: 'bookingportal.withamura.com'
# for public assets such as app/assets
asset_sync:
  FOG_DIRECTORY:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_REGION:
# use for private assets such as client uploads.
carrierwave:
  FOG_DIRECTORY:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_REGION:
redis:
  host: localhost
  port: 6379
  db: 0
  namespace: booking_portal_generic
  password:
sidekiq:
  username:
  password:
smtp:
  user_name:
  password:
  authentication:
  address:
  port:
  domain:
global:
  SECRET_KEY_BASE:
db:
  database:
  hosts:
  options:
    user:
    password:
    auth_source:
    ssl:
razorpay:
  key:
  secret:
pusher:
  pusher_api_app_id: "568634"
  pusher_api_key: "5dc34608bfcefde0e495"
  pusher_api_secret: "2796b4e60ccae832e378"
  pusher_api_cluster: "ap2"
selldo:
  # Used for sell.do link's on user for sitevisit, followups in selldo
  base_url: 'https://v2.sell.do'
  user_email:
  user_token:
  # Used for pushing srd & data to sell.do
  api_clients:
    website:
      api_key:
document_sign:
  zoho:
    client_id:
    secret_id:
sfdc:
  client_id:
  client_secret:
  refresh_token:
third_party_inventory:
  base_url:
interakt:
  base_url:
razorpay:
  base_url:
onesignal:
  base_url: "https://onesignal.com"
  app_id:
  api_key:

asset_manager_host: 'http://localhost:8000'

default_cp_manager_id:
