development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: lp-demo
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts:
        - localhost:27017
      options:
        # Change the default write concern. (default = { w: 1 })
        # write:
        #   w: 1

        # Change the default read preference. Valid options for mode are: :secondary,
        # :secondary_preferred, :primary, :primary_preferred, :nearest
        # (default: primary)
        # read:
        #   mode: :secondary_preferred

        # The name of the user for authentication.
        # user: 'user'

        # The password of the user for authentication.
        # password: 'password'

        # The user's database roles.
        # roles:
        #   - 'dbOwner'
  # Configure Mongoid specific options. (optional)
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    # raise_not_found_error: true

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    # scope_overwrite_exception: false

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false
staging:
  clients:
    default:
      database: <%= ENV_CONFIG['db']['database'] %>
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: booking_portal_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: <%= ENV_CONFIG['db']['database'] %>
      hosts:
        - <%= ENV_CONFIG['db']['host1'] %>
        - <%= ENV_CONFIG['db']['host2'] %>
        - <%= ENV_CONFIG['db']['host3'] %>
      options:
        user: <%= ENV_CONFIG['db']['username'] %>
        password: <%= ENV_CONFIG['db']['password'] %>
        ssl: true
        replica_set: <%= ENV_CONFIG['db']['replica'] %>
        auth_source: <%= ENV_CONFIG['db']['auth_source'] %>
        read:
          mode: :primary_preferred
  options:
