# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9334eabee2676152b239a44387a57f530ddd43195e45458c67ae4a2307a5dd8bd9c0021ff0bb182c2e725de1eee0b3400666031b0a384821c2530eacb97f55e3

staging:
  secret_key_base: 9334eabee2676152b239a44387a57f530ddd43195e45458c67ae4a2307a5dd8bd9c0021ff0bb182c2e725de1eee0b3400666031b0a384821c2530eacb97f55e3

test:
  secret_key_base: e3d5f67d14d6c96b0a9660831cb34bb2c89e76aa8d4f09b956305e0d624078803c7871492f063d29f4c455589b2a2a9742ff07e2be88cbb207a7558bdda75679

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV_CONFIG['global']['SECRET_KEY_BASE'] %>
