# DatabaseSeeds::NotificationTemplate.seed Client.last.id, project_id
module DatabaseSeeds
  module NotificationTemplate
    def self.client_based_seed(client_id)
      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", title: "Cancellation request pending", url: "/", name: "cancellation_request_pending", content: "
        <% if requestable.kind_of?(BookingDetail) %>
          A cancellation has been requested on your booking of <%= requestable.name %> at <%= project_unit.project_name %>. Our CRM team is reviewing your request and will get in touch with you shortly.
        <% elsif requestable.kind_of?(Receipt) %>
          A cancellation has been requested on your payment of <%= requestable.name %> . Our CRM team is reviewing your request and will get in touch with you shortly.
        <% end %>"
        ) if Template::NotificationTemplate.where(name: "cancellation_request_pending", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", name: "cancellation_request_resolved", title: "Cancellation request resolved", url: "/", content: "
        <% if requestable.kind_of?(BookingDetail) %>
          We're sorry to see you go. Cancellation request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been processed and your amount will be refunded to you in a few days. To book another unit visit <%= user.dashboard_url %>
        <% elsif requestable.kind_of?(Receipt) %>
          We're sorry to see you go. Cancellation request on your payment <%= requestable.name %> has been processed and your amount will be refunded to you in a few days.
        <% end %>
      ") if Template::NotificationTemplate.where(name: "cancellation_request_resolved", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", name: "cancellation_request_rejected",  title: "Cancellation request rejected", url: "/", content: "
        <% if requestable.kind_of?(BookingDetail) %>
        Cancellation request on your booking of <%= requestable.name %> at <%= project_unit.project_name %> has been rejected.
        <% elsif requestable.kind_of?(Receipt) %>
          Cancellation request on your payment <%= requestable.name %> has been rejected.
        <% end %>
        ") if Template::NotificationTemplate.where(name: "cancellation_request_rejected", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_pending", title: "Swap request pending", url: "/", content: "A swap has been requested on your booking of <%= project_unit.name %> at <%= project_unit.project_name %>. Our CRM team is reviewing your request and will get in touch with you shortly.", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "swap_request_pending", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_resolved",  title: "Swap request resolved", url: "/", content: "Swap request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been processed. We have now blocked <%= I18n.t('global.project_unit') %> <%= alternate_project_unit.name %> for you.", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "swap_request_resolved", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_rejected", title: "Swap request rejected", url: "/", content: "Swap request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been rejected.", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "swap_request_rejected", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_success", title: "Payment Successful", url: "/", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> was successful (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_success", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_failed", title: "Payment failed", url: "/", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> has failed (<%= receipt_id %>).", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_failed", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_pending", title: "Payment pending", url: "/", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> has been collected and will be sent to the <%= user.name %> Team for clearance.", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_pending", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_clearance_pending",  title: "Payment clearance pending", url: "/", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> is under 'Pending Clearance' (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_clearance_pending", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_available_for_refund", title: "Payment available for refund", url: "/", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> is under 'Available For Refund' (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_available_for_refund", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_refunded", title: "Payment refunded", url: "/", content: "Dear <%= user.name %>, your payment (<%= receipt_id %>) of Rs. <%= total_amount %> has been refunded. To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>", data: "{\n  \"name\": \"<%= self.model_name.human %>\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "receipt_refunded", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "booking_blocked", title: "Project Unit has been blocked", url: "/", content: "Congratulations <%= user.name %>, <%= name %> has been blocked.", data: "{\n  \"name\": \"booking\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"booking_blocked\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "booking_blocked", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "booking_confirmed", title: "Booking confirmed", url: "/", content: "Congratulations <%= user.name %>, <%= name %> booking has been confirmedmed booked.", data: "{\n  \"name\": \"booking\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"booking_confirmed\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "booking_confirmed", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "booking_tentative", title: "Booking Tentative", url: "/", content: "Congratulations <%= user.name %>, <%= name %> booking has been tentative booked.", data: "{\n  \"name\": \"booking\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"booking_tentative\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "booking_tentative", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "ChannelPartner", name: "channel_partner_status_active", title: "Account has been approved", url: "/", content: "Your account has been approved.", data: "{\n  \"name\": \"company\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"channel_partner_activated\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "channel_partner_status_active", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "ChannelPartner", name: "channel_partner_status_rejected", title: "Account has been rejected", url: "/", content: "Your account has been rejected for following reason - <%= self.try(:status_change_reason) %>", data: "{\n  \"name\": \"company\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"channel_partner_rejected\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "channel_partner_status_rejected", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "user_status_active_in_company", title: "Account has been approved", url: "/", content: "Your account has been approved.", data: "{\n  \"name\": \"user\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"user_status_in_company_approved\",\n  \"status\": \"<%= self.user_status_in_company %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "user_status_active_in_company", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "user_status_inactive_in_company", title: "Account has been rejected", url: "/", content: "Your account has been rejected for following reason - <%= self.try(:status_change_reason) %>", data: "{\n  \"name\": \"user\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"user_status_in_company_rejected\",\n  \"status\": \"<%= self.user_status_in_company %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "user_status_inactive_in_company", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Sitevisit", name: "site_visit_approval_status_rejected_notification", title: "Sitevisit rejected", url: "/", content: "Walk-in <%= self.try(:lead).try(:name) %> Rejected", data: "{\n  \"name\": \"site_visit\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"walkin_rejected\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "site_visit_approval_status_rejected_notification", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Sitevisit", name: "site_visit_approval_status_approved_notification", title: "Sitevisit approved", url: "/", content: "Walk-in <%= self.try(:lead).try(:name) %> Approved", data: "{\n  \"name\": \"site_visit\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"walkin_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "site_visit_approval_status_approved_notification", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Sitevisit", name: "site_visit_status_paid_notification", title: "Sitevisit paid", url: "/", content: "Walk-in <%= self.try(:lead).try(:name) %> Paid", data: "{\n  \"name\": \"site_visit\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"walkin_paid\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "site_visit_status_paid_notification", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invoice", name: "invoice_rejected", title: "Invoice rejected", url: "/", content: "Brokerage Rejected", data: "{\n  \"name\": \"invoice\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_rejected\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "invoice_rejected", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invoice", name: "invoice_approved", title: "Invoice approved", url: "/", content: "Brokerage Approved", data: "{\n  \"name\": \"invoice\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "invoice_approved", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invoice", name: "invoice_paid", title: "Invoice paid", url: "/", content: "Brokerage Paid", data: "{\n  \"name\": \"invoice\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"invoice_paid\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "invoice_paid", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invoice", name: "booking_detail_approval_status_approved_notification", title: "Booking Approved", url: "/", content: "<%= self.try(:lead).try(:name) %> booking <%= self.try(:name) %> Approved", data: "{\n  \"name\": \"booking\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"booking_approved\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "booking_detail_approval_status_approved_notification", booking_portal_client_id: client_id).blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invoice", name: "booking_detail_approval_status_rejected_notification", title: "Booking rejected", url: "/", content: "<%= self.try(:lead).try(:name) %> booking <%= self.try(:name) %> Rejected. Rejection Reason - <%= self.try(:rejection_reason)  %>", data: "{\n  \"name\": \"booking\",\n  \"id\": \"<%= self.id %>\",\n  \"event\": \"booking_rejected\",\n  \"status\": \"<%= self.status %>\",\n  \"approval_status\": \"<%= (self.try(:approval_status) || \"-\") %>\"\n}") if Template::NotificationTemplate.where(name: "booking_detail_approval_status_rejected_notification", booking_portal_client_id: client_id).blank?


      return Template::NotificationTemplate.where(booking_portal_client_id: client_id).count
    end
  end
end
