# DatabaseSeeds::NotificationTemplate.seed CLient.last.id
module DatabaseSeeds
  module NotificationTemplate
    def self.seed client_id

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", title: "Cancellation request pending", url: "/<%= current_user_role_group %>/all/user_requests", name: "cancellation_request_pending", content: "
        <% if requestable.kind_of?(BookingDetail) %>
          A cancellation has been requested on your booking of <%= requestable.name %> at <%= project_unit.project_name %>. Our CRM team is reviewing your request and will get in touch with you shortly.
        <% elsif requestable.kind_of?(Receipt) %>
          A cancellation has been requested on your payment of <%= requestable.name %> . Our CRM team is reviewing your request and will get in touch with you shortly.
        <% end %>"
        ) if Template::NotificationTemplate.where(name: "cancellation_request_pending").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", name: "cancellation_request_resolved", title: "Cancellation request resolved", url: "/<%= current_user_role_group %>/all/user_requests", content: "
        <% if requestable.kind_of?(BookingDetail) %>
          We're sorry to see you go. Cancellation request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been processed and your amount will be refunded to you in a few days. To book another unit visit <%= user.dashboard_url %>
        <% elsif requestable.kind_of?(Receipt) %>
          We're sorry to see you go. Cancellation request on your payment <%= requestable.name %> has been processed and your amount will be refunded to you in a few days.
        <% end %>
      ") if Template::NotificationTemplate.where(name: "cancellation_request_resolved").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Cancellation", name: "cancellation_request_rejected",  title: "Cancellation request rejected", url: "/<%= current_user_role_group %>/all/user_requests", content: "
        <% if requestable.kind_of?(BookingDetail) %>
        Cancellation request on your booking of <%= requestable.name %> at <%= project_unit.project_name %> has been rejected.
        <% elsif requestable.kind_of?(Receipt) %>
          Cancellation request on your payment <%= requestable.name %> has been rejected.
        <% end %>
        ") if Template::NotificationTemplate.where(name: "cancellation_request_rejected").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_created", title: "Swap request pending", url: "/<%= current_user_role_group %>/all/user_requests", content: "A swap has been requested on your booking of <%= project_unit.name %> at <%= project_unit.project_name %>. Our CRM team is reviewing your request and will get in touch with you shortly.") if Template::NotificationTemplate.where(name: "swap_request_created").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_resolved",  title: "Swap request resolved", url: "/<%= current_user_role_group %>/all/user_requests", content: "Swap request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been processed. We have now blocked <%= I18n.t('global.project_unit') %> <%= alternate_project_unit.name %> for you.") if Template::NotificationTemplate.where(name: "swap_request_resolved").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "UserRequest::Swap", name: "swap_request_rejected", title: "Swap request rejected", url: "/<%= current_user_role_group %>/all/user_requests", content: "Swap request on your booking of <%= project_unit.name %> at <%= project_unit.project_name %> has been rejected.") if Template::NotificationTemplate.where(name: "swap_request_rejected").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_success", title: "Payment Successful", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> was successful (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "receipt_success").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_failed", title: "Payment failed", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> has failed (<%= receipt_id %>).") if Template::NotificationTemplate.where(name: "receipt_failed").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_pending", title: "Payment pending", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> has been collected and will be sent to the <%= user.name %> Team for clearance.") if Template::NotificationTemplate.where(name: "receipt_pending").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_clearance_pending",  title: "Payment clearance pending", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> is under 'Pending Clearance' (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "receipt_clearance_pending").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_available_for_refund", title: "Payment available for refund", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment of Rs. <%= total_amount %> is under 'Available For Refund' (<%= receipt_id %>). To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "receipt_available_for_refund").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "receipt_refunded", title: "Payment refunded", url: "/<%= current_user_role_group %>/receipts", content: "Dear <%= user.name %>, your payment (<%= receipt_id %>) of Rs. <%= total_amount %> has been refunded. To view your receipt visit your Portal Dashboard <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "receipt_refunded").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_6", title: "Only 6 days to go!", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Only 6 days to go! 6 days to being part of <%= project_unit.booking_portal_client.name %>. Click here to pay the pending amount of Rs. <%= project_unit.pending_balance %> for unit <%= name %> and secure your home at <%= project_unit.project_name %>: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_6").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_5", title: "A home, an identity - come home to yours", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "A home, an identity - come home to yours. Only 5 days to go before you miss your home at <%= project_unit.project_name %>! Get it before you regret it. Click here to complete paying the pending amount: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_5").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_4", title: "Complete your payment", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "You buy electronics online, you buy groceries online - why not a home? Complete your pending amount of Rs. <%= project_unit.pending_balance %> for unit <%= name %> at <%= project_unit.project_name %> on the portal, before you miss your home. You've got only 4 days to go! Click to pay: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_4").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_3", title: "A lot can happen in 3 days", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "A lot can happen in 3 days - today, you have a home at the prestigious <%= project_unit.booking_portal_client.name %> reserved in your name. 3 days from now, you could've missed that opportunity. Click here to pay the pending amount of Rs. <%= project_unit.pending_balance %> for unit <%= name %> today: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_3").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_2", title: "2 days to go!", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "2 days to go! 2 days until you've missed your home at <%= project_unit.project_name %> - or, you could be the proud resident of <%= project_unit.booking_portal_client.name %> today. Click here to complete the transaction of Rs. <%= project_unit.pending_balance %> for unit <%= name %>: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_2").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "promote_future_payment_1", title: "Today is your last chance!", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Today's your last chance to call <%= name %> at <%= project_unit.project_name %> your home! Complete the payment today, or the apartment will get auto-released for other users to book it. Click here to complete your payment of Rs. <%= project_unit.pending_balance %>: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "promote_future_payment_1").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "daily_reminder_for_booking_payment", title: "Complete your payment!", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "You have booked your spot among the privileged few in <%= project_unit.project_name %>. Kindly pay the remaining balance to complete the booking process. The due date is just <%= I18n.l(project_unit.auto_release_on) %>. Visit <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "daily_reminder_for_booking_payment").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "project_unit_released", title: "Project Unit released", url: "/dashboard", content: "Dear <%= name %>, you missed out! We regret to inform you that the apartment you shortlisted has been released. Click here if you'd like to re-start the process: <%= dashboard_url %> Your cust ref id is <%= lead_id %>") if Template::NotificationTemplate.where(name: "project_unit_released").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "booking_blocked", title: "Project Unit has been blocked", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Congratulations <%= user.name %>, <%= name %> has been Blocked / Tentative Booked for you for the next <%= project_unit.blocking_days %> days! To own the home, you'll need to pay the pending amount of Rs. <%= project_unit.pending_balance %> within these <%= project_unit.blocking_days %> days. To complete the payment now, click here: <%= user.dashboard_url %>") if Template::NotificationTemplate.where(name: "booking_blocked").blank?
      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "channel_partner_booking_blocked", title: "Booking done by your customer", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Dear <%= user.manager.name %>, <%= user.name %> has blocked unit <%= name %>.") if Template::NotificationTemplate.where(name: "channel_partner_booking_blocked").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "booking_confirmed", title: "Booking confirmed", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Welcome to the <%= project_unit.booking_portal_client.name %> family! You're now the proud owner of <%= name %> at <%= project_unit.project_name %> in <%= project_unit.booking_portal_client.name %>. Our executives will be in touch regarding agreement formalities.") if Template::NotificationTemplate.where(name: "booking_confirmed").blank?
      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "BookingDetail", name: "channel_partner_booking_confirmed", title: "Your customer's booking is confirmed", url: "/<%= current_user_role_group %>/booking_details/<%= id.to_s %>", content: "Dear <%= user.manager.name %>, <%= user.name %> has booked unit <%= name %>.") if Template::NotificationTemplate.where(name: "channel_partner_booking_confirmed").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "user_registered_by_channel_partner", title: "Account confirmation by <%= manager.name %>", url: "/dashboard", content: "<%= manager.name %> has registered you with <%= booking_portal_client.name %>. To confirm your account with this partner, please click <%= confirmation_url %>. You can also confirm your account using your phone & <%= I18n.t('global.otp') %>.") if Template::NotificationTemplate.where(name: "user_registered_by_channel_partner").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "channel_partner_user_registered", content: "Dear <%= name %>, thank you for registering as a Channel Partner at <%= booking_portal_client.name %>. To confirm your account, please click <%= confirmation_url %>. You can also confirm your account using your phone & <%= I18n.t('global.otp') %>.") if Template::NotificationTemplate.where(name: "channel_partner_user_registered").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "User", name: "user_registered", title: "Channel Partner registration successful", url: "/dashboard", content: "Dear <%= name %>, thank you for registering at <%= booking_portal_client.name %>. To confirm your account, please click <%= confirmation_url %>. You can also confirm your account using your phone & <%= I18n.t('global.otp') %>.") if Template::NotificationTemplate.where(name: "user_registered").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Client", name: "daily_sms_report", title: "Today's update", url: "/dashboard", content: 'Blocked: <%= ProjectUnit.where(status: "blocked").count %>. Tentative: <%= ProjectUnit.where(status: "booked_tentative").count %>. Confirmed: <%= ProjectUnit.where(status: "booked_confirmed").count %>. Blocked Today: <%= ProjectUnit.where(blocked_on: Date.today).count %>.     *subject to cancellations') if Template::NotificationTemplate.where(name: "daily_sms_report").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Invitation", name: "referral_invitation", title: "Referral invitation", url: "/dashboard", content: "Dear <%= self.name %>, You are invited in <%= self.booking_portal_client.booking_portal_domains.join(', ') %> Please click here. <%= Rails.application.routes.url_helpers.register_url(custom_referral_code: self.referred_by.referral_code) %> or user <%= self.referred_by.referral_code %> code for sign up.") if Template::NotificationTemplate.where(name: "referral_invitation").blank?

      Template::NotificationTemplate.create(booking_portal_client_id: client_id, subject_class: "Receipt", name: "daily_payments_report", title: "Today's payment report", url: "/dashboard", content: '[<%= Date.current.strftime("%v") %>] Today you received <%= self.class.todays_payments_count %> payments') if Template::NotificationTemplate.where(name: "daily_payments_report").blank?

      # reminder templates
      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'not_confirmed_day_1', title: "Confirm your account", url: "/dashboard", content: "Thank you for your interest in <%= current_project.name %>. Your KYC generation is not complete. For more information about the project, call <%= self.booking_portal_client.support_number %>")   if ::Template::NotificationTemplate.where(name: "not_confirmed_day_1").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'not_confirmed_day_3', title: "Confirm your account", url: "/dashboard", content: "Don’t be late! <%= current_project.name %> is offering rewards on a first come first serve basis. Register today and avail special benefits, call <%= self.booking_portal_client.support_number %> for more information.")  if ::Template::NotificationTemplate.where(name: "not_confirmed_day_3").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'not_confirmed_day_5', title: "Confirm your account", url: "/dashboard", content: "You are doing your best to build your kids’ dream home. We are doing our best to make it a reality. Register today and get greater discounts, call <%= self.booking_portal_client.support_number %> for more information.")  if ::Template::NotificationTemplate.where(name: "not_confirmed_day_5").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_payment_hour_1', title: "Payment pending", url: "/<%= current_user_role_group %>/receipts", content: "Alert: Your KYC registration is not yet complete. Complete payment to lock your spot in the queue and avail unique benefits, call <%= self.booking_portal_client.support_number %> for more information.")  if ::Template::NotificationTemplate.where(name: "no_payment_hour_1").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_payment_day_1', title: "Payment pending", url: "/<%= current_user_role_group %>/receipts", content: "Reminder: Your KYC registration is not yet complete. Lock your spot in the queue and avail unique benefits, call <%= self.booking_portal_client.support_number %> for more information.")  if ::Template::NotificationTemplate.where(name: "no_payment_day_1").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_payment_day_3', title: "Payment pending", url: "/<%= current_user_role_group %>/receipts", content: "Reminder: You are one step away from booking your spot, call on <%= self.booking_portal_client.support_number %> for more information.")  if ::Template::NotificationTemplate.where(name: "no_payment_day_3").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_booking_day_4', title: "Booking pending", url: "/dashboard", content: "In case if you need a home loan, select loan preference and upload KYC so that our loan representative can help you.")  if ::Template::NotificationTemplate.where(name: "no_booking_day_4").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_booking_day_5', title: "Booking pending", url: "/dashboard", content: "Earn additional discounts at <%= current_project.name %> by completing your profile to help us know you better.")  if ::Template::NotificationTemplate.where(name: "no_booking_day_5").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_booking_day_6', title: "Booking pending", url: "/dashboard", content: "Thank for showing your preference for the loan requirement for your dream home at <%= current_project.name %>. We have a host financial partners who are offering home loans at competitive rates.")  if ::Template::NotificationTemplate.where(name: "no_booking_day_6").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'no_booking_day_7', title: "Booking pending", url: "/dashboard", content: "Earn additional discounts by referring your 3 friends at <%= current_project.name %>.")  if ::Template::NotificationTemplate.where(name: "no_booking_day_7").blank?

      Template::NotificationTemplate.create!(booking_portal_client_id: client_id, subject_class: "User", name: 'payment_link', title: "Payment link", url: "/dashboard", content: ' <% if self.manager.present? && self.manager_role?("channel_partner") %>
            Thank you for your interest in <%= self.booking_portal_client.name %>. <%= self.manager_name %> has registered you. To make your first payment, please click here: <%= short_url(self.payment_link) %> <% end %>')  if ::Template::NotificationTemplate.where(name: "payment_link").blank?

      return Template::NotificationTemplate.where(booking_portal_client_id: client_id).count
    end
  end
end
